In [11]:
import pandas as pd
import numpy as np
import math
import random

In [21]:
df_new = pd.read_csv("./LinearData.csv")

In [22]:
df_new.shape

(292160, 3)

In [ ]:
Click Matrix

No. of Click should be between 0-5
If not Recommended then it will be NAN

In [4]:
new_df.head(40)

    User Id  Loan  Recommendation_Rank
0         1    19                    1
1         1    20                    2
2         1    10                    3
3         1    13                    4
4         1     6                    5
5         2     3                    1
6         2    14                    2
7         2     2                    3
8         2     7                    4
9         2    15                    5
10        3     3                    1
11        3     2                    2
12        3     5                    3
13        3     7                    4
14        3    14                    5
15        4     5                    1
16        4     7                    2
17        4     6                    3
18        4     8                    4
19        4     9                    5
20        5     4                    1
21        5     7                    2
22        5     2                    3
23        5    14                    4
24        5     5                    5
25        6    14                    1
26        6     6                    2
27        6    15                    3
28        6     4                    4
29        6    20                    5
30        7     4                    1
31        7     8                    2
32        7     3                    3
33        7     2                    4
34        7     7                    5
35        8    14                    1
36        8    19                    2
37        8    22                    3
38        8    10                    4
39        8    17                    5

In [23]:
# Create an empty dataframe to store the transformed data
new_df = pd.DataFrame(columns=['User Id', 'Loan', 'Recommendation_Rank', 'CTR'])

# Iterate over each row in the initial dataframe
for index, row in df_new.iloc[:50].iterrows():
    # Extract User Id and Recommendations list
    user_id = row['UserId']
    recommendations = row['Recommendations'][1:-1].split(',')
    
    # Iterate over each loan in the recommendations list
    for indx,loan in enumerate(recommendations, start=1):
        # Append a new row to the new dataframe for each loan
        new_df = pd.concat([new_df, pd.DataFrame({'User Id': [user_id], 'Loan': [loan], 'Recommendation_Rank':[indx],'CTR':[random.randint(1, 5)]})], ignore_index=True)

# Convert User Id column to integer type
new_df['User Id'] = new_df['User Id'].astype(int)

KeyError: 'UserId'

In [19]:
print(random.randint(1, 5))

4

Form Matrix

No of forms filled Any of the 1 form filled from M form Recommended
If not Recommended then it will be NaN.